//========================================[ALU]===============================================
./verilog/Project10_mini_CPU/src_mini_CPU/ALU/ALU_Control.v
./verilog/Project10_mini_CPU/src_mini_CPU/ALU/ALU_MUX.v
./verilog/Project10_mini_CPU/src_mini_CPU/ALU/ALU.v
./verilog/Project10_mini_CPU/src_mini_CPU/ALU/calculate_group.v
./verilog/Project10_mini_CPU/src_mini_CPU/ALU/logical_group.v
./verilog/Project10_mini_CPU/src_mini_CPU/ALU/shift_group.v
//========================================[Register]===============================================
./verilog/Project10_mini_CPU/src_mini_CPU/Register/Data_Memory.v
./verilog/Project10_mini_CPU/src_mini_CPU/Register/Register_file.v
./verilog/Project10_mini_CPU/src_mini_CPU/Register/Pipe_reg_1clk_control.v
./verilog/Project10_mini_CPU/src_mini_CPU/Register/Pipe_reg_1clk.v
./verilog/Project10_mini_CPU/src_mini_CPU/Register/Pipe_reg_1clk_en.v
//========================================[MUX]===============================================
./verilog/Project10_mini_CPU/src_mini_CPU/MUX/ALUsrc_MUX.v
./verilog/Project10_mini_CPU/src_mini_CPU/MUX/CPU_MUX.v
./verilog/Project10_mini_CPU/src_mini_CPU/MUX/PC_MUX.v
//========================================[]===============================================
./verilog/Project10_mini_CPU/src_mini_CPU/ImmGen.v
./verilog/Project10_mini_CPU/src_mini_CPU/Instruction_Memory.v
./verilog/Project10_mini_CPU/src_mini_CPU/Main_Decoder.v
./verilog/Project10_mini_CPU/src_mini_CPU/Hazard_Unit.v
./verilog/Project10_mini_CPU/src_mini_CPU/Early_Jump_Unit.v
//========================================[pc]===============================================
./verilog/Project10_mini_CPU/src_mini_CPU/PC/PC_Adder.v
./verilog/Project10_mini_CPU/src_mini_CPU/PC/PC_reg.v
./verilog/Project10_mini_CPU/src_mini_CPU/PC/PC_Target.v
./verilog/Project10_mini_CPU/src_mini_CPU/PC/PCSrc.v
//========================================[FADD]===============================================
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/barrel_shifter.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/CLA.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/comparator.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/Cond_Inverter.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/Exception_Handler_ADD.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/EXPO_CAL.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/EXPO_MUX.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/EXPO_SUB.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/FADD_core.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/LZD.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/Magnitude_Restoration.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/Mode_Detector.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/Normalization_Controller.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/Rounding.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/SIGN.v
//========================================[FPU common]===============================================
./verilog/Project10_mini_CPU/src_mini_CPU/FPU_common/FPU_unpack.v
./verilog/Project10_mini_CPU/src_mini_CPU/FPU_common/MUX.v
./verilog/Project10_mini_CPU/src_mini_CPU/FPU_common/FPU_Control.v
//========================================[FMUL]===============================================
./verilog/Project10_mini_CPU/src_mini_CPU/FMUL/Exception_Handler.v
./verilog/Project10_mini_CPU/src_mini_CPU/FMUL/MUL_EXPO_ADD.v
./verilog/Project10_mini_CPU/src_mini_CPU/FMUL/MUL_EXPO.v
./verilog/Project10_mini_CPU/src_mini_CPU/FMUL/MUL_SIGN.v
./verilog/Project10_mini_CPU/src_mini_CPU/FMUL/FMUL_core.v
./verilog/Project10_mini_CPU/src_mini_CPU/FMUL/Multiplier.v
./verilog/Project10_mini_CPU/src_mini_CPU/FMUL/Normalization_MUL.v
//========================================[Top module]===============================================
./verilog/Project10_mini_CPU/src_mini_CPU/Top_module/FPU.v
./verilog/Project10_mini_CPU/src_mini_CPU/TOP_module/Pipeline_CPU.v
//========================================[TB]===============================================
./verilog/Project10_mini_CPU/tb/Pipeline_CPU_tb.v
