./verilog/Project10_mini_CPU/src_mini_CPU/ALU/ALU_Control.v
./verilog/Project10_mini_CPU/src_mini_CPU/ALU/ALU_MUX.v
./verilog/Project10_mini_CPU/src_mini_CPU/ALU/ALU.v
./verilog/Project10_mini_CPU/src_mini_CPU/ALU/calculate_group.v
./verilog/Project10_mini_CPU/src_mini_CPU/ALU/logical_group.v
./verilog/Project10_mini_CPU/src_mini_CPU/ALU/shift_group.v
./verilog/Project10_mini_CPU/src_mini_CPU/Register/Data_Memory.v
./verilog/Project10_mini_CPU/src_mini_CPU/Register/Register_file.v
./verilog/Project10_mini_CPU/src_mini_CPU/Register/Pipe_reg_1clk_control.v
./verilog/Project10_mini_CPU/src_mini_CPU/MUX/ALUsrc_MUX.v
./verilog/Project10_mini_CPU/src_mini_CPU/MUX/CPU_MUX.v
./verilog/Project10_mini_CPU/src_mini_CPU/ImmGen.v
./verilog/Project10_mini_CPU/src_mini_CPU/Instruction_Memory.v
./verilog/Project10_mini_CPU/src_mini_CPU/Main_Decoder.v
./verilog/Project10_mini_CPU/src_mini_CPU/PC/PC_Adder.v
./verilog/Project10_mini_CPU/src_mini_CPU/MUX/PC_MUX.v
./verilog/Project10_mini_CPU/src_mini_CPU/PC/PC_reg.v
./verilog/Project10_mini_CPU/src_mini_CPU/PC/PC_Target.v
./verilog/Project10_mini_CPU/src_mini_CPU/PC/PCSrc.v
./verilog/Project10_mini_CPU/src_mini_CPU/TOP_module/Pipeline_CPU.v
./verilog/Project10_mini_CPU/tb/Pipeline_CPU_tb.v
