./verilog/Project10_mini_CPU/src_mini_CPU/FADD/barrel_shifter.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/CLA.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/comparator.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/Cond_Inverter.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/Exception_Handler_ADD.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/EXPO_CAL.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/EXPO_MUX.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/EXPO_SUB.v
./verilog/Project10_mini_CPU/src_mini_CPU/common/FPU_unpack.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/FPU_ADD.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/LZD.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/Magnitude_Restoration.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/Mode_Detector.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/Normalization_Controller.v
./verilog/Project10_mini_CPU/src_mini_CPU/common/Pipe_reg_1clk.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/Rounding.v
./verilog/Project10_mini_CPU/src_mini_CPU/FADD/SIGN.v
./verilog/Project10_mini_CPU/tb/FPU_ADD_tb.v
